<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The Library</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <style>
  	a {text-decoration:none;}
  </style>
</head>
<body>


<div id="secondary">

<?php
if (!isset($this->disableLogin)) {
	echo $this->authForm($this->loginForm,$this->errorMessage); 
}
?>
	
    </div>	
 <div id="maincontent">

<?php echo $this->layout()->content; ?>  
    </div>

    
 
</body>
</html>